### ISSUE TITLE
Set up repository and issue tracker to support RP18 V2.0 release

### ISSUE THREAD

**Issue by AndyClifton** [IEA-Wind-Task-32/RP18-floating-lidar-systems#1]
As discussed with Task 32 members in a call on 27.3.2020, we need a way to track feedback and prioritise edits / updates to the RP18.

**Comment by AndyClifton** [comment]
Things to do. 

 - Get feedback on the existing document:
    - [x] Capture the existing document as a release
    - [x] Set up issues
    - [x] Set up labels
    - [ ] Create list of people to solicit feedback from

 - Set up the tools to help prepare for the next release
    - [x] Create a project board
    - [x] Set up milestones

**Comment by AndyClifton** [comment]
Closing this and moving remaining open "to-do" to issue #3 as it is an unrelated task.
